### ISSUE TITLE
ImportError cannot import name 'Munch' from 'radical.utils

### ISSUE THREAD

**Issue by Andyyoung0507** [radical-project/radical.dreamer#7]
Sorry, I downloaded this project and built the environment.  When I tried to run the example _run_session_peer.py_ , the error is 'Exception has occurred: ImportError
cannot import name 'Munch' from 'radical.utils' (../miniconda3/envs/dreamer/lib/python3.7/site-packages/radical/utils/__init__.py)' . What is the cause of the problem?

**Comment by mtitov** [comment]
Hello, can you please install `radical.utils` of version 1.11.1 first, since RADICAL-DREAMER wasn't adapted to later releases yet. This will be updated soon

**Comment by mtitov** [comment]
@Andyyoung0507 new releases of `radical.utils` (RU) are supported in devel-branch (`pip install git+https://github.com/radical-project/radical.dreamer.git@devel`), thus the latest version of RU can be used

**Comment by Andyyoung0507** [comment]
Thank you. It works when I install the  devel branch.
